version: 2
updates:
  - package-ecosystem: gomod
    directory: /bot
    schedule:
      interval: weekly
  - package-ecosystem: nuget
    directory: /capture
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
