//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCapture_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUCapture_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deafened.
        /// </summary>
        public static string BadgeDeafened {
            get {
                return ResourceManager.GetString("BadgeDeafened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ghost channel.
        /// </summary>
        public static string BadgeInGhostChannel {
            get {
                return ResourceManager.GetString("BadgeInGhostChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linked.
        /// </summary>
        public static string BadgeLinked {
            get {
                return ResourceManager.GetString("BadgeLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muted.
        /// </summary>
        public static string BadgeMuted {
            get {
                return ResourceManager.GetString("BadgeMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not linked.
        /// </summary>
        public static string BadgeNotLinked {
            get {
                return ResourceManager.GetString("BadgeNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the capture version that matches the bot..
        /// </summary>
        public static string CaptureRefusedIncompatible {
            get {
                return ResourceManager.GetString("CaptureRefusedIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an administrator for a new code with /au capture pair, then pair again..
        /// </summary>
        public static string CaptureRefusedNewCode {
            get {
                return ResourceManager.GetString("CaptureRefusedNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AUVC bot refused this capture.
        /// </summary>
        public static string CaptureRefusedTitle {
            get {
                return ResourceManager.GetString("CaptureRefusedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your config was reset successfully..
        /// </summary>
        public static string ConfigResetMessage {
            get {
                return ResourceManager.GetString("ConfigResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config reset.
        /// </summary>
        public static string ConfigResetTitle {
            get {
                return ResourceManager.GetString("ConfigResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoMuteUs.
        /// </summary>
        public static string ConnectionStatus_AUTOMUTEUS {
            get {
                return ResourceManager.GetString("ConnectionStatus.AUTOMUTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC.
        /// </summary>
        public static string ConnectionStatus_AUVC_BOT {
            get {
                return ResourceManager.GetString("ConnectionStatus.AUVC BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string ConnectionStatus_DISCORD_BOT {
            get {
                return ResourceManager.GetString("ConnectionStatus.DISCORD BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Bot.
        /// </summary>
        public static string ConnectionStatus_USER_BOT {
            get {
                return ResourceManager.GetString("ConnectionStatus.USER BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The special people that make capture possible.
        /// </summary>
        public static string ContributorsHeader {
            get {
                return ResourceManager.GetString("ContributorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string ContributorsTitle {
            get {
                return ResourceManager.GetString("ContributorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have detected that you are running an unsupported version of the game. This may or may not work..
        /// </summary>
        public static string CrackDetectedMessage {
            get {
                return ResourceManager.GetString("CrackDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crack detected.
        /// </summary>
        public static string CrackDetectedTitle {
            get {
                return ResourceManager.GetString("CrackDetectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To disable debug mode, we need to restart..
        /// </summary>
        public static string DebugModeOffRestart {
            get {
                return ResourceManager.GetString("DebugModeOffRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable debug mode, we need to restart..
        /// </summary>
        public static string DebugModeOnRestart {
            get {
                return ResourceManager.GetString("DebugModeOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code.
        /// </summary>
        public static string GameCodeTooltip {
            get {
                return ResourceManager.GetString("GameCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game code.
        /// </summary>
        public static string GameCodeWatermark {
            get {
                return ResourceManager.GetString("GameCodeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCUSSION.
        /// </summary>
        public static string GameState_DISCUSSION {
            get {
                return ResourceManager.GetString("GameState.DISCUSSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENDED.
        /// </summary>
        public static string GameState_ENDED {
            get {
                return ResourceManager.GetString("GameState.ENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBBY.
        /// </summary>
        public static string GameState_LOBBY {
            get {
                return ResourceManager.GetString("GameState.LOBBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string GameState_MENU {
            get {
                return ResourceManager.GetString("GameState.MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        public static string GameState_TASKS {
            get {
                return ResourceManager.GetString("GameState.TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string GameState_UNKNOWN {
            get {
                return ResourceManager.GetString("GameState.UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current status.
        /// </summary>
        public static string GameStateTooltip {
            get {
                return ResourceManager.GetString("GameStateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string GameStateWatermark {
            get {
                return ResourceManager.GetString("GameStateWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string LaterText {
            get {
                return ResourceManager.GetString("LaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing code: .
        /// </summary>
        public static string ManualConnectionCode {
            get {
                return ResourceManager.GetString("ManualConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair with the AUVC bot.
        /// </summary>
        public static string ManualConnectionHeader {
            get {
                return ResourceManager.GetString("ManualConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot address: .
        /// </summary>
        public static string ManualConnectionHost {
            get {
                return ResourceManager.GetString("ManualConnectionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair.
        /// </summary>
        public static string ManualConnectionSubmitButton {
            get {
                return ResourceManager.GetString("ManualConnectionSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair with the AUVC bot.
        /// </summary>
        public static string ManualConnectTooltip {
            get {
                return ResourceManager.GetString("ManualConnectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current map.
        /// </summary>
        public static string MapTooltip {
            get {
                return ResourceManager.GetString("MapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MapWatermark {
            get {
                return ResourceManager.GetString("MapWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: this address uses plain HTTP to another computer, so the credential crosses the network unencrypted. Ask the bot&apos;s administrator for an https:// address..
        /// </summary>
        public static string PairedInClearWarning {
            get {
                return ResourceManager.GetString("PairedInClearWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is paired with the AUVC bot and connects by itself from now on..
        /// </summary>
        public static string PairedMessage {
            get {
                return ResourceManager.GetString("PairedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired.
        /// </summary>
        public static string PairedTitle {
            get {
                return ResourceManager.GetString("PairedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the pairing code from /au capture pair..
        /// </summary>
        public static string PairingEmptyCode {
            get {
                return ResourceManager.GetString("PairingEmptyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That pairing code has expired. Ask an administrator for a new one with /au capture pair..
        /// </summary>
        public static string PairingExpired {
            get {
                return ResourceManager.GetString("PairingExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing failed.
        /// </summary>
        public static string PairingFailedTitle {
            get {
                return ResourceManager.GetString("PairingFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not the address of a bot. Enter it in the form {0}..
        /// </summary>
        public static string PairingInvalidAddress {
            get {
                return ResourceManager.GetString("PairingInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That pairing code is not valid. Ask an administrator for a new one with /au capture pair..
        /// </summary>
        public static string PairingRejected {
            get {
                return ResourceManager.GetString("PairingRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach the AUVC bot at {0}. Check the address and that the bot is running..
        /// </summary>
        public static string PairingUnreachable {
            get {
                return ResourceManager.GetString("PairingUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get AutoMuteUs premium.
        /// </summary>
        public static string PremiumTooltip {
            get {
                return ResourceManager.GetString("PremiumTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reset your config.
        ///This cannot be undone..
        /// </summary>
        public static string ResetConfigQuestion {
            get {
                return ResourceManager.GetString("ResetConfigQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ResetConfigQuestionTitle {
            get {
                return ResourceManager.GetString("ResetConfigQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting config.
        /// </summary>
        public static string ResettingConfigTitle {
            get {
                return ResourceManager.GetString("ResettingConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartText {
            get {
                return ResourceManager.GetString("RestartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version:.
        /// </summary>
        public static string SettingsAboutTabAppVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors: .
        /// </summary>
        public static string SettingsAboutTabContributorsButton {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show contributors.
        /// </summary>
        public static string SettingsAboutTabContributorsButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsAboutTabHeader {
            get {
                return ResourceManager.GetString("SettingsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version:.
        /// </summary>
        public static string SettingsAboutTabLatestVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        public static string SettingsDebugOpenLogsFolderButton {
            get {
                return ResourceManager.GetString("SettingsDebugOpenLogsFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        public static string SettingsDebugTabDebugModeSwitch {
            get {
                return ResourceManager.GetString("SettingsDebugTabDebugModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string SettingsDebugTabHeader {
            get {
                return ResourceManager.GetString("SettingsDebugTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload offsets.
        /// </summary>
        public static string SettingsDebugTabReloadOffsetsButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabReloadOffsetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Config.
        /// </summary>
        public static string SettingsDebugTabResetConfigButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabResetConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always copy game code.
        /// </summary>
        public static string SettingsGeneralTabAlwaysCopyGameCode {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysCopyGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string SettingsGeneralTabAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Server.
        /// </summary>
        public static string SettingsGeneralTabAPIServer {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new versions.
        /// </summary>
        public static string SettingsGeneralTabCheckForUpdate {
            get {
                return ResourceManager.GetString("SettingsGeneralTabCheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus window on connect.
        /// </summary>
        public static string SettingsGeneralTabFocusOnConnect {
            get {
                return ResourceManager.GetString("SettingsGeneralTabFocusOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneralTabHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsGeneralTabLanguageHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Windows.
        /// </summary>
        public static string SettingsGeneralTabLanguageSameAsWindows {
            get {
                return ResourceManager.GetString("SettingsGeneralTabLanguageSameAsWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup memes.
        /// </summary>
        public static string SettingsGeneralTabStartupMemes {
            get {
                return ResourceManager.GetString("SettingsGeneralTabStartupMemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the settings window.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot on this PC is not running.
        /// </summary>
        public static string StatusBotNotRunning {
            get {
                return ResourceManager.GetString("StatusBotNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open “Bot” → Status and click “Restart the bot”..
        /// </summary>
        public static string StatusBotNotRunningNext {
            get {
                return ResourceManager.GetString("StatusBotNotRunningNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot reports a problem: {0}.
        /// </summary>
        public static string StatusBotProblem {
            get {
                return ResourceManager.GetString("StatusBotProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the bot ….
        /// </summary>
        public static string StatusConnecting {
            get {
                return ResourceManager.GetString("StatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this takes long, check that the bot is running and reachable..
        /// </summary>
        public static string StatusConnectingRemoteNext {
            get {
                return ResourceManager.GetString("StatusConnectingRemoteNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC cannot read this Among Us version.
        /// </summary>
        public static string StatusGameNotSupported {
            get {
                return ResourceManager.GetString("StatusGameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among Us was probably updated. Install the newest AUVC version; a line at the top links to it as soon as one is out..
        /// </summary>
        public static string StatusGameNotSupportedNext {
            get {
                return ResourceManager.GetString("StatusGameNotSupportedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Among Us is running.
        /// </summary>
        public static string StatusInMenu {
            get {
                return ResourceManager.GetString("StatusInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a lobby or create one..
        /// </summary>
        public static string StatusInMenuNext {
            get {
                return ResourceManager.GetString("StatusInMenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is linked yet.
        /// </summary>
        public static string StatusNobodyLinked {
            get {
                return ResourceManager.GetString("StatusNobodyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC manages only linked players. They pick their crewmate in the text channel, or link them under “Bot” → Players..
        /// </summary>
        public static string StatusNobodyLinkedNext {
            get {
                return ResourceManager.GetString("StatusNobodyLinkedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not paired with a bot.
        /// </summary>
        public static string StatusNotPaired {
            get {
                return ResourceManager.GetString("StatusNotPaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a code with /au capture pair and enter it with the pairing button at the top..
        /// </summary>
        public static string StatusNotPairedNext {
            get {
                return ResourceManager.GetString("StatusNotPairedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC is not set up yet.
        /// </summary>
        public static string StatusNotSetUp {
            get {
                return ResourceManager.GetString("StatusNotSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click “Set up” at the top..
        /// </summary>
        public static string StatusNotSetUpNext {
            get {
                return ResourceManager.GetString("StatusNotSetUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone stays as they are. Continue with /au session resume..
        /// </summary>
        public static string StatusPausedNext {
            get {
                return ResourceManager.GetString("StatusPausedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} players linked. AUVC manages only linked players..
        /// </summary>
        public static string StatusReadyCounted {
            get {
                return ResourceManager.GetString("StatusReadyCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC follows the game..
        /// </summary>
        public static string StatusReadyNext {
            get {
                return ResourceManager.GetString("StatusReadyNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot refused this app.
        /// </summary>
        public static string StatusRefused {
            get {
                return ResourceManager.GetString("StatusRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open “Bot” → Status and restart the bot..
        /// </summary>
        public static string StatusRefusedLocalNext {
            get {
                return ResourceManager.GetString("StatusRefusedLocalNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a new code with /au capture pair and pair again..
        /// </summary>
        public static string StatusRefusedRemoteNext {
            get {
                return ResourceManager.GetString("StatusRefusedRemoteNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC is not managing voice.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with /au session start, or switch on automatic start under “Bot” → Channels..
        /// </summary>
        public static string StatusStoppedNext {
            get {
                return ResourceManager.GetString("StatusStoppedNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Among Us.
        /// </summary>
        public static string StatusWaitingForGame {
            get {
                return ResourceManager.GetString("StatusWaitingForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Among Us on this PC..
        /// </summary>
        public static string StatusWaitingForGameNext {
            get {
                return ResourceManager.GetString("StatusWaitingForGameNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app and the bot do not match.
        /// </summary>
        public static string StatusWrongVersion {
            get {
                return ResourceManager.GetString("StatusWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the AUVC version that matches the bot..
        /// </summary>
        public static string StatusWrongVersionNext {
            get {
                return ResourceManager.GetString("StatusWrongVersionNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUCapture.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUVC {0} is available..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking ….
        /// </summary>
        public static string UpdateChecking {
            get {
                return ResourceManager.GetString("UpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched off.
        /// </summary>
        public static string UpdateCheckOff {
            get {
                return ResourceManager.GetString("UpdateCheckOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development build.
        /// </summary>
        public static string UpdateDevelopmentBuild {
            get {
                return ResourceManager.GetString("UpdateDevelopmentBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the release page.
        /// </summary>
        public static string UpdateOpenReleasePage {
            get {
                return ResourceManager.GetString("UpdateOpenReleasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string UpdateUpToDate {
            get {
                return ResourceManager.GetString("UpdateUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Among Us.
        /// </summary>
        public static string WaitingForAmongUs {
            get {
                return ResourceManager.GetString("WaitingForAmongUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Lobby.
        /// </summary>
        public static string WaitingForLobby {
            get {
                return ResourceManager.GetString("WaitingForLobby", resourceCulture);
            }
        }
    }
}
