package text

var english = map[Key]string{
	NotInServer:        "❌ `/au` commands can only be used inside a Discord server.",
	StorageUnavailable: "❌ AUVC configuration storage is unavailable.",
	InvalidCommand:     "❌ Invalid `/au` command: %v",
	ServerUnavailable:  "❌ Discord guild information is unavailable. Please try again.",
	NotAuthorized:      "❌ You need the configured AUVC admin role or Discord Administrator permission for this command.",
	CommandFailed:      "❌ AUVC could not complete this command: %v",

	ChannelsSaved: "✅ AUVC channels saved.\n%s",
	ChannelList:   "Main: <#%s>\nGhost: <#%s>\nControl: %s",
	NotConfigured: "not configured",
	AdminsSet:     "✅ AUVC administrators set to <@&%s>.",
	ConfigReset:   "✅ Guild configuration reset to AUVC defaults. Persistent player links were kept.",
	SettingsSaved: "✅ AUVC settings saved.\n%s",
	SettingsList: "**AUVC settings**\nEnabled: %s\n%s\nAdmin role: %s\nVoice policy: `%s`\n" +
		"Auto-move ghosts: %s\nEnforce channels: %s\nCapture timeout: %ds (`%s`)\nAuto-start: %s\nLanguage: %s\nConfig version: %d",
	Yes:              "yes",
	No:               "no",
	Linked:           "✅ Linked <@%s> to Among Us player `%s`.",
	Unlinked:         "✅ Removed persistent Among Us links for <@%s>.",
	FallbackDatabase: "✅ SQLite reachable; schema migration %d applied.",
	FallbackReady:    "✅ Guild configuration is valid and has both voice channels.",
	FallbackNeedsBot: "⚠️ Discord, permission and capture checks need a running bot and are unavailable here.",

	ProblemMissing:       "missing",
	ProblemOneOf:         "must be one of %v, got %q",
	ProblemTimeoutBounds: "must be between %d and %d seconds, got %d",
	ProblemSameChannel:   "must differ from the main voice channel",
	ProblemDisabled:      "the bot is disabled for this guild",
	ProblemNotSet:        "not set; run /au setup channels",

	PairingCode: "🔗 Pairing code: `%s`\n\n" +
		"Type it into the AUVC capture app on the PC that runs Among Us. " +
		"It works once and expires %s (in %s). Running this command again replaces it.",
	NothingToRevoke: "✅ Nothing to revoke: no capture was paired. Any outstanding pairing code was cancelled.",
	Revoked: "✅ Revoked %d capture credential(s), cancelled any outstanding pairing code " +
		"and disconnected any capture app that was still connected. " +
		"Run `/au capture pair` to connect a capture app again.",
	CaptureUnavailable:        "⚠️ `/au capture %s` is registered, but capture pairing is unavailable in this build.",
	CaptureNeverConnected:     "✅ Capture is paired but has never connected yet.",
	CapturePaired:             "✅ Capture is paired. Last seen %s.",
	CaptureNotPaired:          "❌ No capture is paired. Run `/au capture pair` to connect one.",
	CaptureCodeWaiting:        "⚠️ A pairing code is waiting to be used; it expires %s.",
	CaptureRevokedCredentials: "%d revoked credential(s) on record.",
	CaptureInstalls:           "%d capture installs are paired.",

	SessionUnavailable: "⚠️ `/au session %s` is registered, but session control is unavailable in this build.",
	NotSetUp:           "❌ AUVC is not set up for this server yet. Run `/au setup channels` first.",
	AlreadyManaging:    "✅ Already managing voice. Nothing changed.",
	NowManaging:        "✅ Now managing voice for this server.",
	NotManaging:        "✅ Not managing voice. Nothing changed.",
	StoppedManaging:    "✅ Stopped managing voice. Everyone has been unmuted and returned to the main channel.",
	AlreadyPaused:      "✅ Already paused. Nothing changed.",
	NothingToPause:     "⚠️ Nothing was being managed, so there was nothing to pause. Run `/au session start` to begin.",
	PausedNow: "⏸️ Paused. Players stay exactly where they are until `/au session resume`, " +
		"and the game is still being followed.",
	Resumed:          "▶️ Resumed. Voice has been brought into line with the game as it stands.",
	StatusManaging:   "✅ Managing voice.",
	StatusPaused:     "⏸️ Paused. The game is being followed, but Discord is left alone.",
	StatusStopped:    "⏹️ Not managing voice. Run `/au session start` to begin.",
	StatusNoGame:     "No game data yet. Connect the capture app with `/au capture pair`.",
	StatusPhase:      "Phase: **%s**",
	StatusPlayers:    "Players: %d alive, %d dead.",
	StatusNoChannels: "⚠️ Voice channels are not configured. Run `/au setup channels`.",

	PhaseMenu:          "Menu",
	PhaseLobby:         "Lobby",
	PhaseTasks:         "Tasks",
	PhaseDiscussion:    "Discussion",
	PhaseBetweenRounds: "Between rounds",
	PhaseUnknown:       "Unknown",
	ModeRunning:        "running",
	ModePaused:         "paused",
	ModeStopped:        "stopped",

	CrewmateMenuFailed: "❌ AUVC could not build the crewmate menu: %v",
	NoLobbyYet: "There is no Among Us lobby to choose from yet. " +
		"Join a lobby while the AUVC app is running and run `/au link` again, " +
		"or type your name with `/au link player:<name>`.",
	CrewmateOnlyInServer: "❌ Crewmates can only be chosen inside a Discord server.",
	ChoiceNotUnderstood:  "❌ That choice was not understood. Please choose again.",
	PlayerLeftLobby:      "❌ `%s` is not in the lobby any more. Please choose again from the updated menu.",
	ChoiceNotAllowed:     "❌ You are not allowed to choose a crewmate here.",
	ChoiceNotSaved:       "❌ AUVC could not save your choice: %v",

	CheckDiscord:        "Discord",
	CheckDatabase:       "Database",
	CheckConfiguration:  "Configuration",
	CheckEnabled:        "Enabled",
	CheckMainChannel:    "Main voice channel",
	CheckGhostChannel:   "Ghost voice channel",
	CheckControlChannel: "Control text channel",
	CheckPermissions:    "Permissions",
	CheckCrewmateMenu:   "Crewmate menu",
	CheckCapture:        "Capture",
	CheckHeartbeat:      "Heartbeat",
	CheckProtocol:       "Protocol",
	CheckGameState:      "Game state",
	CheckBuild:          "Build",

	DoctorNothingChecked:         "⚠️ Nothing was checked.",
	DoctorProblemsAndWarnings:    "❌ %d problem(s) and %d warning(s).",
	DoctorProblems:               "❌ %d problem(s).",
	DoctorWarnings:               "⚠️ %d warning(s); AUVC can still run.",
	DoctorAllGood:                "✅ Everything checks out.",
	DoctorNoSession:              "no Discord session",
	DoctorNoSessionFix:           "Restart AUVC and check `DISCORD_BOT_TOKEN`.",
	DoctorGuildNotCached:         "connected, but this server is not in the bot's cache",
	DoctorGuildNotCachedFix:      "Remove and re-invite the bot, then try again.",
	DoctorConnected:              "connected and watching **%s**",
	DoctorDatabaseUnreachable:    "SQLite is not reachable: %s",
	DoctorDatabaseUnreachableFix: "Check `AUVC_DATABASE_PATH` and that the volume is writable.",
	DoctorDatabaseReachable:      "SQLite reachable, schema migration %d applied",
	DoctorConfigUnreadable:       "could not be read: %s",
	DoctorConfigInvalidFix:       "Fix it with `/au settings`, or start over with `/au setup reset`.",
	DoctorDisabled:               "AUVC is switched off for this server",
	DoctorDisabledFix:            "Turn it on with `/au settings voice enabled:true`.",
	DoctorNotSet:                 "not set",
	DoctorSetChannelFix:          "Set it with `/au setup channels`.",
	DoctorControlChannelFix: "Set one with `/au setup channels`: players choose their crewmate there, " +
		"and AUVC warns you when capture stops.",
	DoctorChannelUnconfirmed:     "configured, but Discord is unavailable to confirm it",
	DoctorChannelMissing:         "<#%s> is configured but AUVC cannot see it",
	DoctorChannelMissingFix:      "The channel may have been deleted. Set it again with `/au setup channels`.",
	DoctorPermissionsGranted:     "all five voice permissions are granted on both channels",
	DoctorPermissionsFix:         "Grant the missing permissions to the AUVC role, on the role or on the channel.",
	DoctorCrewmatePermissionsFix: "Grant the missing permissions to the AUVC role on the text channel, or invite the bot again from the AUVC app.",
	DoctorCrewmateUnavailable:    "not available in this build",
	DoctorCrewmateUnavailableFix: "Players can still link themselves with `/au link player:<name>`.",
	DoctorCrewmatePictures:       "in <#%s>, with %d of %d crewmate pictures so far",
	DoctorCrewmatePicturesFix:    "The pictures upload when AUVC starts. If the number does not grow, the bot log says why.",
	DoctorCrewmateReady:          "in <#%s>, with every crewmate picture",
	DoctorCaptureUnreadable:      "pairing state could not be read: %s",
	DoctorCaptureNotPaired:       "no capture app is paired",
	DoctorCaptureNotPairedFix:    "Run `/au capture pair` and type the code into the capture app.",
	DoctorCapturePaired:          "paired",
	DoctorHeartbeatNever:         "capture is paired but has not connected since AUVC started",
	DoctorHeartbeatNeverFix:      "Start the capture app on the PC running Among Us.",
	DoctorHeartbeatStale:         "nothing heard for %s, past the %s timeout",
	DoctorHeartbeatStaleFix:      "Check that the capture app is still running and can reach this bot.",
	DoctorHeartbeatRecent:        "last message %s ago (timeout %s)",
	DoctorProtocol:               "this bot speaks version %d, and capture is connected on it",
	DoctorNoGameData:             "no game data yet",
	DoctorNoGameDataFix:          "Start Among Us with the capture app running.",
	DoctorGameState:              "%s, %d alive and %d dead, session %s",
	DoctorStartSessionFix:        "Start managing voice with `/au session start`.",

	PermissionsMissing:      "AUVC is missing Discord permissions:\n",
	PermissionMissingLine:   "- **%s** on the %s: %s\n",
	PermissionChannelsJoin:  " and the ",
	PurposeMainChannel:      "main voice channel",
	PurposeGhostChannel:     "ghost voice channel",
	PurposeTextChannel:      "text channel",
	WithoutViewVoiceChannel: "AUVC cannot see the channel and does not know who is in it",
	WithoutConnect:          "AUVC cannot move anyone into the channel",
	WithoutMoveMembers:      "dead players are not moved to the ghost channel and are not returned at the end of a round",
	WithoutMuteMembers:      "living players are not muted during tasks",
	WithoutDeafenMembers:    "living players can hear the dead talking during tasks",
	WithoutViewTextChannel:  "AUVC cannot see the channel, so neither the crewmate menu nor warnings appear there",
	WithoutSendMessages:     "AUVC cannot post the crewmate menu or warn you when capture stops",
	WithoutEmbedLinks:       "AUVC cannot post the crewmate menu",

	DescribeAU:               "Among Us Voice Controller",
	DescribeSetup:            "First-time setup",
	DescribeSetupChannels:    "Choose the voice and control channels",
	DescribeMainChannel:      "Where living players belong",
	DescribeGhostChannel:     "Where dead players are moved",
	DescribeControlChannel:   "Where the bot posts game status",
	DescribeSetupPermissions: "Choose who may administer the bot",
	DescribeAdminRole:        "Role allowed to change settings",
	DescribeSetupReset:       "Reset this guild to the default configuration",
	DescribeConfirmReset:     "Confirm that the current configuration is discarded",
	DescribeSettings:         "Inspect and change settings",
	DescribeSettingsShow:     "Show the current configuration",
	DescribeSettingsPreset:   "Apply a named configuration preset",
	DescribePolicyPreset:     "Voice policy preset",
	DescribeSettingsVoice:    "Change voice handling",
	DescribeEnabled:          "Whether the bot manages voice at all",
	DescribePolicy:           "Voice policy",
	DescribeSettingsGhosts:   "Change how dead players are handled",
	DescribeAutoMoveGhosts:   "Move dead players to the ghost channel",
	DescribeEnforce:          "Return players who switch channels themselves",
	DescribeSettingsSafety:   "Change what happens when capture goes quiet",
	DescribeTimeout:          "Seconds without capture before the fail-safe runs",
	DescribeTimeoutAction:    "What to do when capture times out",
	DescribeAutoStart:        "Start a session automatically when a game begins",
	DescribeSettingsExport:   "Export the current configuration",
	DescribeCapture:          "Manage the capture connection",
	DescribeCapturePair:      "Create a one-time pairing code for the capture app",
	DescribeCaptureStatus:    "Show the capture connection status",
	DescribeCaptureRevoke:    "Revoke capture access for this guild",
	DescribeConfirmRevoke:    "Confirm that the capture app must pair again",
	DescribeSession:          "Control the running session",
	DescribeSessionStart:     "Start managing voice for the current game",
	DescribeSessionStop:      "Stop managing voice and release everyone",
	DescribeSessionPause:     "Temporarily stop applying voice changes",
	DescribeSessionResume:    "Resume applying voice changes",
	DescribeSessionStatus:    "Show the session status",
	DescribeLink:             "Link a Discord user to an Among Us player",
	DescribePlayer:           "Among Us player name; leave it out to choose your crewmate from a menu",
	DescribeUser:             "Discord user; defaults to you",
	DescribeUnlink:           "Remove a link",
	DescribeDoctor:           "Check configuration, permissions and connectivity",
	DescribeVersion:          "Show the AUVC version",

	LanguageSameAsDiscord:    "Same as Discord",
	DescribeSettingsLanguage: "Choose the language of the crewmate message and the notices",
	DescribeLanguage:         "Same as Discord follows the server language set in Discord",

	BoardTitle:       "Choose your crewmate",
	BoardWaiting:     "Waiting for players. Join a lobby in Among Us while the AUVC app is running.",
	BoardIntro:       "Pick the crewmate you are playing in the menu below. AUVC then mutes and moves the right person.",
	BoardFree:        "free",
	BoardTaken:       "taken",
	BoardFooter:      "Picked the wrong one? Choose again, or choose \"%s\".",
	BoardUnlink:      "Unlink me",
	BoardUnlinkHint:  "Remove your link",
	BoardPlaceholder: "Choose your crewmate",

	ColorRed:     "Red",
	ColorBlue:    "Blue",
	ColorGreen:   "Green",
	ColorPink:    "Pink",
	ColorOrange:  "Orange",
	ColorYellow:  "Yellow",
	ColorBlack:   "Black",
	ColorWhite:   "White",
	ColorPurple:  "Purple",
	ColorBrown:   "Brown",
	ColorCyan:    "Cyan",
	ColorLime:    "Lime",
	ColorMaroon:  "Maroon",
	ColorRose:    "Rose",
	ColorBanana:  "Banana",
	ColorGray:    "Gray",
	ColorTan:     "Tan",
	ColorCoral:   "Coral",
	ColorUnknown: "Unknown colour",

	NoticeCaptureStopped: "⚠️ The capture app stopped responding.",
	NoticePausedByChoice: "The session is paused and players have been left exactly as they are, " +
		"because this server is configured with `capture_timeout_action: pause`. " +
		"Run `/au session stop` to release everyone.",
	NoticeReleaseFailed:   "AUVC could not unmute everyone automatically: %s",
	NoticeReleased:        "Everyone has been unmuted and returned to the main channel.",
	NoticeResumesOnItsOwn: "The session is paused and resumes on its own when capture comes back.",
	NoticeCaptureBack:     "✅ The capture app is back. AUVC is following the game again.",

	BoardMap:   "Map",
	BoardPhase: "Phase",
	BoardCode:  "Lobby code",
}
