package text

var german = map[Key]string{
	NotInServer:        "❌ `/au`-Befehle funktionieren nur in einem Discord-Server.",
	StorageUnavailable: "❌ Die Einstellungen von AUVC sind gerade nicht erreichbar.",
	InvalidCommand:     "❌ Ungültiger `/au`-Befehl: %v",
	ServerUnavailable:  "❌ Discord liefert gerade keine Daten zu diesem Server. Versuch es gleich noch einmal.",
	NotAuthorized:      "❌ Für diesen Befehl brauchst du die AUVC-Admin-Rolle oder die Discord-Berechtigung Administrator.",
	CommandFailed:      "❌ AUVC konnte den Befehl nicht ausführen: %v",

	ChannelsSaved: "✅ Kanäle gespeichert.\n%s",
	ChannelList:   "Hauptkanal: <#%s>\nGeisterkanal: <#%s>\nTextkanal: %s",
	NotConfigured: "nicht gesetzt",
	AdminsSet:     "✅ AUVC verwalten jetzt <@&%s>.",
	ConfigReset:   "✅ Die Einstellungen dieses Servers sind zurückgesetzt. Die Verknüpfungen der Spieler bleiben.",
	SettingsSaved: "✅ Einstellungen gespeichert.\n%s",
	SettingsList: "**AUVC-Einstellungen**\nEingeschaltet: %s\n%s\nAdmin-Rolle: %s\nSprachsteuerung: `%s`\n" +
		"Tote verschieben: %s\nKanäle durchsetzen: %s\nWartezeit auf die App: %ds (`%s`)\nAutomatisch starten: %s\nSprache: %s\nKonfigurationsversion: %d",
	Yes:              "ja",
	No:               "nein",
	Linked:           "✅ <@%s> spielt jetzt `%s`.",
	Unlinked:         "✅ Die Verknüpfungen von <@%s> sind entfernt.",
	FallbackDatabase: "✅ SQLite erreichbar, Schema-Migration %d angewendet.",
	FallbackReady:    "✅ Die Einstellungen sind gültig, beide Sprachkanäle sind gesetzt.",
	FallbackNeedsBot: "⚠️ Discord, Berechtigungen und App lassen sich nur mit laufendem Bot prüfen.",

	ProblemMissing:       "fehlt",
	ProblemOneOf:         "muss eins von %v sein, ist aber %q",
	ProblemTimeoutBounds: "muss zwischen %d und %d Sekunden liegen, ist aber %d",
	ProblemSameChannel:   "muss ein anderer Kanal sein als der Hauptkanal",
	ProblemDisabled:      "der Bot ist für diesen Server ausgeschaltet",
	ProblemNotSet:        "nicht gesetzt; führe /au setup channels aus",

	PairingCode: "🔗 Kopplungscode: `%s`\n\n" +
		"Gib ihn in der AUVC-App auf dem PC ein, auf dem Among Us läuft. " +
		"Er gilt einmal und läuft %s ab (in %s). Führst du den Befehl noch einmal aus, ersetzt ein neuer Code diesen.",
	NothingToRevoke: "✅ Nichts zu widerrufen: Es war keine App gekoppelt. Ein offener Kopplungscode wurde verworfen.",
	Revoked: "✅ %d Zugang/Zugänge der App widerrufen, einen offenen Kopplungscode verworfen " +
		"und eine noch verbundene App getrennt. " +
		"Mit `/au capture pair` verbindest du wieder eine App.",
	CaptureUnavailable:        "⚠️ `/au capture %s` gibt es, aber diese Version kann keine App koppeln.",
	CaptureNeverConnected:     "✅ Eine App ist gekoppelt, hat sich aber noch nie verbunden.",
	CapturePaired:             "✅ Eine App ist gekoppelt. Zuletzt gesehen: %s.",
	CaptureNotPaired:          "❌ Keine App ist gekoppelt. Mit `/au capture pair` verbindest du eine.",
	CaptureCodeWaiting:        "⚠️ Ein Kopplungscode wartet noch darauf, benutzt zu werden. Er läuft %s ab.",
	CaptureRevokedCredentials: "%d widerrufene Zugänge gespeichert.",
	CaptureInstalls:           "%d Apps sind gekoppelt.",

	SessionUnavailable: "⚠️ `/au session %s` gibt es, aber diese Version kann keine Sitzung steuern.",
	NotSetUp:           "❌ AUVC ist für diesen Server noch nicht eingerichtet. Führe zuerst `/au setup channels` aus.",
	AlreadyManaging:    "✅ AUVC steuert die Sprachkanäle bereits. Nichts geändert.",
	NowManaging:        "✅ AUVC steuert jetzt die Sprachkanäle dieses Servers.",
	NotManaging:        "✅ AUVC steuert gerade nichts. Nichts geändert.",
	StoppedManaging:    "✅ AUVC steuert nicht mehr. Alle sind freigegeben und zurück im Hauptkanal.",
	AlreadyPaused:      "✅ Schon pausiert. Nichts geändert.",
	NothingToPause:     "⚠️ AUVC hat nichts gesteuert, also gibt es nichts zu pausieren. Mit `/au session start` geht es los.",
	PausedNow: "⏸️ Pausiert. Alle bleiben genau so, wie sie sind, bis `/au session resume`. " +
		"Das Spiel wird weiter verfolgt.",
	Resumed:          "▶️ Weiter geht's. Die Sprachkanäle passen jetzt wieder zum aktuellen Spielstand.",
	StatusManaging:   "✅ AUVC steuert die Sprachkanäle.",
	StatusPaused:     "⏸️ Pausiert. Das Spiel wird verfolgt, in Discord ändert sich nichts.",
	StatusStopped:    "⏹️ AUVC steuert gerade nichts. Mit `/au session start` geht es los.",
	StatusNoGame:     "Noch keine Spieldaten. Verbinde die App mit `/au capture pair`.",
	StatusPhase:      "Phase: **%s**",
	StatusPlayers:    "Spieler: %d lebendig, %d tot.",
	StatusNoChannels: "⚠️ Die Sprachkanäle sind nicht eingerichtet. Führe `/au setup channels` aus.",

	PhaseMenu:          "Menü",
	PhaseLobby:         "Lobby",
	PhaseTasks:         "Tasks",
	PhaseDiscussion:    "Meeting",
	PhaseBetweenRounds: "Zwischen den Runden",
	PhaseUnknown:       "Unbekannt",
	ModeRunning:        "läuft",
	ModePaused:         "pausiert",
	ModeStopped:        "gestoppt",

	CrewmateMenuFailed: "❌ AUVC konnte das Crewmate-Menü nicht erstellen: %v",
	NoLobbyYet: "Es gibt noch keine Among-Us-Lobby zur Auswahl. " +
		"Geh in eine Lobby, während die AUVC-App läuft, und führe `/au link` erneut aus, " +
		"oder gib deinen Namen mit `/au link player:<name>` ein.",
	CrewmateOnlyInServer: "❌ Crewmates lassen sich nur in einem Discord-Server wählen.",
	ChoiceNotUnderstood:  "❌ Diese Auswahl wurde nicht verstanden. Bitte wähle noch einmal.",
	PlayerLeftLobby:      "❌ `%s` ist nicht mehr in der Lobby. Bitte wähle im aktualisierten Menü neu.",
	ChoiceNotAllowed:     "❌ Du darfst hier keinen Crewmate wählen.",
	ChoiceNotSaved:       "❌ AUVC konnte deine Auswahl nicht speichern: %v",

	CheckDiscord:        "Discord",
	CheckDatabase:       "Datenbank",
	CheckConfiguration:  "Einstellungen",
	CheckEnabled:        "Eingeschaltet",
	CheckMainChannel:    "Hauptkanal",
	CheckGhostChannel:   "Geisterkanal",
	CheckControlChannel: "Textkanal",
	CheckPermissions:    "Berechtigungen",
	CheckCrewmateMenu:   "Crewmate-Menü",
	CheckCapture:        "App",
	CheckHeartbeat:      "Lebenszeichen",
	CheckProtocol:       "Protokoll",
	CheckGameState:      "Spielstand",
	CheckBuild:          "Version",

	DoctorNothingChecked:         "⚠️ Es wurde nichts geprüft.",
	DoctorProblemsAndWarnings:    "❌ %d Problem(e) und %d Warnung(en).",
	DoctorProblems:               "❌ %d Problem(e).",
	DoctorWarnings:               "⚠️ %d Warnung(en); AUVC läuft trotzdem.",
	DoctorAllGood:                "✅ Alles in Ordnung.",
	DoctorNoSession:              "keine Verbindung zu Discord",
	DoctorNoSessionFix:           "Starte AUVC neu und prüfe `DISCORD_BOT_TOKEN`.",
	DoctorGuildNotCached:         "verbunden, aber dieser Server fehlt im Zwischenspeicher des Bots",
	DoctorGuildNotCachedFix:      "Entferne den Bot, lade ihn neu ein und versuch es dann noch einmal.",
	DoctorConnected:              "verbunden mit **%s**",
	DoctorDatabaseUnreachable:    "SQLite ist nicht erreichbar: %s",
	DoctorDatabaseUnreachableFix: "Prüfe `AUVC_DATABASE_PATH` und ob dort geschrieben werden darf.",
	DoctorDatabaseReachable:      "SQLite erreichbar, Schema-Migration %d angewendet",
	DoctorConfigUnreadable:       "ließen sich nicht lesen: %s",
	DoctorConfigInvalidFix:       "Korrigiere das mit `/au settings` oder fang mit `/au setup reset` neu an.",
	DoctorDisabled:               "AUVC ist für diesen Server ausgeschaltet",
	DoctorDisabledFix:            "Schalte es mit `/au settings voice enabled:true` ein.",
	DoctorNotSet:                 "nicht gesetzt",
	DoctorGhostNotUsed:           "nicht genutzt: Tote bleiben stumm im Hauptkanal",
	DoctorSetChannelFix:          "Lege ihn mit `/au setup channels` fest.",
	DoctorControlChannelFix: "Lege ihn mit `/au setup channels` fest: Dort wählen die Spieler ihren Crewmate, " +
		"und AUVC warnt dich, wenn die App verstummt.",
	DoctorChannelUnconfirmed:     "gesetzt, aber ohne Discord nicht zu bestätigen",
	DoctorChannelMissing:         "<#%s> ist gesetzt, aber AUVC sieht den Kanal nicht",
	DoctorChannelMissingFix:      "Vielleicht wurde der Kanal gelöscht. Lege ihn mit `/au setup channels` neu fest.",
	DoctorPermissionsGranted:     "alle fünf Sprach-Berechtigungen sind in beiden Kanälen erteilt",
	DoctorPermissionsFix:         "Gib der AUVC-Rolle die fehlenden Berechtigungen, an der Rolle oder am Kanal.",
	DoctorCrewmatePermissionsFix: "Gib der AUVC-Rolle die fehlenden Berechtigungen im Textkanal, oder lade den Bot aus der AUVC-App neu ein.",
	DoctorCrewmateUnavailable:    "in dieser Version nicht verfügbar",
	DoctorCrewmateUnavailableFix: "Spieler können sich weiter mit `/au link player:<name>` verknüpfen.",
	DoctorCrewmatePictures:       "in <#%s>, bisher %d von %d Crewmate-Bildern",
	DoctorCrewmatePicturesFix:    "Die Bilder werden beim Start von AUVC hochgeladen. Wächst die Zahl nicht, steht der Grund im Log des Bots.",
	DoctorCrewmateReady:          "in <#%s>, mit allen Crewmate-Bildern",
	DoctorCaptureUnreadable:      "der Kopplungsstand ließ sich nicht lesen: %s",
	DoctorCaptureNotPaired:       "keine App gekoppelt",
	DoctorCaptureNotPairedFix:    "Führe `/au capture pair` aus und gib den Code in der App ein.",
	DoctorCapturePaired:          "gekoppelt",
	DoctorHeartbeatNever:         "die App ist gekoppelt, hat sich seit dem Start von AUVC aber nicht verbunden",
	DoctorHeartbeatNeverFix:      "Starte die App auf dem PC, auf dem Among Us läuft.",
	DoctorHeartbeatStale:         "seit %s nichts gehört, länger als die Wartezeit von %s",
	DoctorHeartbeatStaleFix:      "Prüfe, ob die App noch läuft und diesen Bot erreicht.",
	DoctorHeartbeatRecent:        "letzte Nachricht vor %s (Wartezeit %s)",
	DoctorProtocol:               "dieser Bot spricht Version %d, und die App ist damit verbunden",
	DoctorNoGameData:             "noch keine Spieldaten",
	DoctorNoGameDataFix:          "Starte Among Us, während die App läuft.",
	DoctorGameState:              "%s, %d lebendig und %d tot, Sitzung %s",
	DoctorStartSessionFix:        "Starte die Steuerung mit `/au session start`.",

	PermissionsMissing:      "AUVC fehlen Discord-Berechtigungen:\n",
	PermissionMissingLine:   "- **%s** für %s: %s\n",
	PermissionChannelsJoin:  " und ",
	PurposeMainChannel:      "den Hauptkanal",
	PurposeGhostChannel:     "den Geisterkanal",
	PurposeTextChannel:      "den Textkanal",
	WithoutViewVoiceChannel: "AUVC sieht den Kanal nicht und weiß nicht, wer darin ist",
	WithoutConnect:          "AUVC kann niemanden in den Kanal verschieben",
	WithoutMoveMembers:      "Tote kommen nicht in den Geisterkanal und am Ende einer Runde nicht zurück",
	WithoutMuteMembers:      "Lebende werden während der Tasks nicht stummgeschaltet",
	WithoutDeafenMembers:    "Lebende hören während der Tasks, was die Toten sagen",
	WithoutViewTextChannel:  "AUVC sieht den Kanal nicht, dort erscheinen weder das Crewmate-Menü noch Warnungen",
	WithoutSendMessages:     "AUVC kann weder das Crewmate-Menü posten noch warnen, wenn die App verstummt",
	WithoutEmbedLinks:       "AUVC kann das Crewmate-Menü nicht posten",

	DescribeAU:               "Among Us Voice Controller",
	DescribeSetup:            "Ersteinrichtung",
	DescribeSetupChannels:    "Sprachkanäle und Textkanal wählen",
	DescribeMainChannel:      "Hier sind alle, die noch leben",
	DescribeGhostChannel:     "Hierhin kommen die Toten",
	DescribeControlChannel:   "Hier schreibt der Bot zum Spiel",
	DescribeSetupPermissions: "Wählen, wer den Bot verwalten darf",
	DescribeAdminRole:        "Rolle, die Einstellungen ändern darf",
	DescribeSetupReset:       "Einstellungen dieses Servers zurücksetzen",
	DescribeConfirmReset:     "Bestätigen, dass die aktuellen Einstellungen verworfen werden",
	DescribeSettings:         "Einstellungen ansehen und ändern",
	DescribeSettingsShow:     "Aktuelle Einstellungen anzeigen",
	DescribeSettingsPreset:   "Eine Vorlage für die Einstellungen anwenden",
	DescribePolicyPreset:     "Vorlage für die Sprachsteuerung",
	DescribeSettingsVoice:    "Sprachsteuerung ändern",
	DescribeEnabled:          "Ob der Bot die Sprachkanäle überhaupt steuert",
	DescribePolicy:           "Art der Sprachsteuerung",
	DescribeSettingsGhosts:   "Ändern, was mit Toten passiert",
	DescribeAutoMoveGhosts:   "Tote in den Geisterkanal verschieben",
	DescribeEnforce:          "Wer selbst den Kanal wechselt, wird zurückgeholt",
	DescribeSettingsSafety:   "Ändern, was passiert, wenn die App verstummt",
	DescribeTimeout:          "Sekunden ohne App, bis die Sicherung greift",
	DescribeTimeoutAction:    "Was passiert, wenn die App zu lange schweigt",
	DescribeAutoStart:        "Sitzung automatisch starten, wenn ein Spiel beginnt",
	DescribeSettingsExport:   "Aktuelle Einstellungen exportieren",
	DescribeCapture:          "Verbindung zur App verwalten",
	DescribeCapturePair:      "Einmaligen Kopplungscode für die App erstellen",
	DescribeCaptureStatus:    "Stand der Verbindung zur App anzeigen",
	DescribeCaptureRevoke:    "Zugang der App zu diesem Server widerrufen",
	DescribeConfirmRevoke:    "Bestätigen, dass die App neu gekoppelt werden muss",
	DescribeSession:          "Laufende Sitzung steuern",
	DescribeSessionStart:     "Sprachkanäle für das aktuelle Spiel steuern",
	DescribeSessionStop:      "Steuerung beenden und alle freigeben",
	DescribeSessionPause:     "Sprachsteuerung vorübergehend anhalten",
	DescribeSessionResume:    "Sprachsteuerung fortsetzen",
	DescribeSessionStatus:    "Stand der Sitzung anzeigen",
	DescribeLink:             "Ein Discord-Mitglied mit einer Among-Us-Figur verknüpfen",
	DescribePlayer:           "Name in Among Us; weglassen, um deinen Crewmate aus einem Menü zu wählen",
	DescribeUser:             "Discord-Mitglied; ohne Angabe du selbst",
	DescribeUnlink:           "Verknüpfung entfernen",
	DescribeDoctor:           "Einstellungen, Berechtigungen und Verbindungen prüfen",
	DescribeVersion:          "AUVC-Version anzeigen",

	LanguageSameAsDiscord:    "Wie Discord",
	DescribeSettingsLanguage: "Sprache der Crewmate-Nachricht und der Hinweise wählen",
	DescribeLanguage:         "„Wie Discord“ folgt der Serversprache, die in Discord eingestellt ist",

	BoardTitle:       "Wähle deinen Crewmate",
	BoardWaiting:     "Warte auf Spieler. Geh in Among Us in eine Lobby, während die AUVC-App läuft.",
	BoardIntro:       "Wähle unten im Menü den Crewmate, den du spielst. AUVC schaltet dann die richtige Person stumm und verschiebt sie.",
	BoardFree:        "frei",
	BoardTaken:       "vergeben",
	BoardFooter:      "Falsch gewählt? Wähle neu oder „%s“.",
	BoardUnlink:      "Verknüpfung lösen",
	BoardUnlinkHint:  "Deine Verknüpfung entfernen",
	BoardPlaceholder: "Wähle deinen Crewmate",

	ColorRed:     "Rot",
	ColorBlue:    "Blau",
	ColorGreen:   "Grün",
	ColorPink:    "Pink",
	ColorOrange:  "Orange",
	ColorYellow:  "Gelb",
	ColorBlack:   "Schwarz",
	ColorWhite:   "Weiß",
	ColorPurple:  "Lila",
	ColorBrown:   "Braun",
	ColorCyan:    "Cyan",
	ColorLime:    "Hellgrün",
	ColorMaroon:  "Weinrot",
	ColorRose:    "Rosa",
	ColorBanana:  "Banane",
	ColorGray:    "Grau",
	ColorTan:     "Beige",
	ColorCoral:   "Koralle",
	ColorUnknown: "Unbekannte Farbe",

	NoticeCaptureStopped: "⚠️ Die AUVC-App antwortet nicht mehr.",
	NoticePausedByChoice: "Die Sitzung ist pausiert, und alle bleiben genau so, wie sie sind, " +
		"weil dieser Server `capture_timeout_action: pause` eingestellt hat. " +
		"Mit `/au session stop` gibst du alle frei.",
	NoticeReleaseFailed:   "AUVC konnte nicht alle automatisch freigeben: %s",
	NoticeReleased:        "Alle sind freigegeben und zurück im Hauptkanal.",
	NoticeResumesOnItsOwn: "Die Sitzung ist pausiert und läuft von selbst weiter, sobald die App wieder da ist.",
	NoticeCaptureBack:     "✅ Die AUVC-App ist wieder da. AUVC verfolgt das Spiel wieder.",

	BoardMap:   "Karte",
	BoardPhase: "Phase",
	BoardCode:  "Lobby-Code",
}
