#!/usr/bin/env python3
"""Fail when a new reference to upstream infrastructure appears in AUVC.

AUVC must run without depending on hosts the AutoMuteUs project controls. Some
references still exist and are tracked in issues #33 and #44; they are recorded
in a baseline so this check passes today while refusing anything new.

Provenance is explicitly not the target. UPSTREAM.md, LICENSES/,
THIRD_PARTY_NOTICES.md and the documentation name upstream on purpose and are
exempt. This is about what the running product reaches for, not about hiding
where the code came from.

Usage:
    python scripts/check_upstream_references.py
    python scripts/check_upstream_references.py --update   # after removing one
"""

from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
BASELINE = Path(__file__).resolve().parent / "upstream_references_baseline.txt"

# Hosts and services the AutoMuteUs project controls. A match means the running
# product would reach for infrastructure AUVC cannot fix, replace or keep alive.
PATTERNS = (
    re.compile(r"automute\.us", re.IGNORECASE),
    re.compile(r"raw\.githubusercontent\.com/(?:automuteus|denverquane)", re.IGNORECASE),
    re.compile(r"automuteus\.crowdin\.com", re.IGNORECASE),
)

# Paths that name upstream deliberately: provenance, licences and documentation.
EXEMPT_PREFIXES = (
    "UPSTREAM.md",
    "THIRD_PARTY_NOTICES.md",
    "LICENSE",
    "LICENSES/",
    "CHANGELOG.md",
    "README.md",
    "SECURITY.md",
    "docs/",
    "scripts/check_upstream_references.py",
    "scripts/upstream_references_baseline.txt",
    "bot/LICENSE",
    "capture/LICENSE",
)


def tracked_files() -> list[str]:
    output = subprocess.check_output(["git", "-C", str(ROOT), "ls-files", "-z"])
    return [name for name in output.decode("utf-8").split("\0") if name]


def is_exempt(path: str) -> bool:
    return any(path == prefix or path.startswith(prefix) for prefix in EXEMPT_PREFIXES)


def find_references() -> set[tuple[str, str]]:
    """Return every (path, matched text) pair outside the exempt paths."""
    found: set[tuple[str, str]] = set()

    for path in tracked_files():
        if is_exempt(path):
            continue

        try:
            text = (ROOT / path).read_text(encoding="utf-8", errors="ignore")
        except (OSError, UnicodeDecodeError):
            # Binary assets cannot carry a URL this check would act on.
            continue

        for pattern in PATTERNS:
            for match in pattern.finditer(text):
                found.add((path, match.group(0).lower()))

    return found


def read_baseline() -> set[tuple[str, str]]:
    if not BASELINE.exists():
        return set()

    entries: set[tuple[str, str]] = set()
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        path, _, match = line.partition("\t")
        entries.add((path, match))
    return entries


def write_baseline(entries: set[tuple[str, str]]) -> None:
    header = (
        "# Upstream infrastructure references that still exist, one per line as\n"
        "# path<TAB>match. Generated by scripts/check_upstream_references.py --update.\n"
        "#\n"
        "# Each entry is a reference AUVC still makes to a host the AutoMuteUs\n"
        "# project controls. They are tracked by issues #33 and #44. The list may\n"
        "# only ever shrink: adding a new reference fails the build.\n"
    )
    body = "".join(f"{path}\t{match}\n" for path, match in sorted(entries))
    BASELINE.write_text(header + body, encoding="utf-8", newline="\n")


def main() -> int:
    found = find_references()

    if "--update" in sys.argv[1:]:
        write_baseline(found)
        print(f"Baseline updated: {len(found)} references recorded.")
        return 0

    baseline = read_baseline()
    added = sorted(found - baseline)
    removed = sorted(baseline - found)

    if added:
        print("New references to upstream infrastructure:")
        for path, match in added:
            print(f"  {path}: {match}")
        print()
        print("AUVC must not gain new dependencies on hosts it does not control.")
        print("Remove the reference, or if it is unavoidable, record why in the")
        print("relevant issue and run: python scripts/check_upstream_references.py --update")

    if removed:
        if added:
            print()
        print("References that no longer exist but are still in the baseline:")
        for path, match in removed:
            print(f"  {path}: {match}")
        print()
        print("Good news, but the baseline has to stay accurate. Run:")
        print("  python scripts/check_upstream_references.py --update")

    if added or removed:
        return 1

    print(f"PASS: no new upstream infrastructure references ({len(found)} known, tracked in #33 and #44)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
